/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.math.abs
import org.example.day02_is_safe

fun day01_part1(): Int {

    // Read input
    val lines = read_lines("src/main/resources/day01.txt")

    // Convert lines to pairs of ints
    val pairs: List<Pair<Int, Int>> = lines.map { line: String ->
        val parts = line.split("   ")
        val n1 = parts[0].toInt()
        val n2 = parts[1].toInt()

        Pair(n1, n2)
    }

    // Split up pairs into their own lists and sort them
    val listA = pairs.map { pair -> pair.first }.sorted()
    val listB = pairs.map { pair -> pair.second }.sorted()

    // Get the sum of distances
    var sum = 0
    for (i in listA.indices) {
        sum += abs(listA[i] - listB[i])
    }

    return sum
}

fun day01_part2(): Int {

    // Read input
    val lines = read_lines("src/main/resources/day01.txt")

    // Convert lines to pairs of ints
    val pairs: List<Pair<Int, Int>> = lines.map { line: String ->
        val parts = line.split("   ")
        val n1 = parts[0].toInt()
        val n2 = parts[1].toInt()

        Pair(n1, n2)
    }

    // Split up pairs into their own lists
    val listA = pairs.map { pair -> pair.first }
    val listB = pairs.map { pair -> pair.second }

    // Build frequency map from right list
    var freqMap = HashMap<Int, Int>()
    listB.forEach { n -> 
        if (freqMap.containsKey(n)) {
            val old = freqMap.getValue(n)
            freqMap.replace(n, old+1)
        } else {
            freqMap.put(n, 1)
        }
    }

    // Calculate similarity using frequency map
    var similarity = 0
    listA.forEach { n ->
        if (freqMap.containsKey(n)) {
            val occurences = freqMap.getValue(n)
            similarity += n * occurences
        }
    }

    return similarity
}

fun day02_part1(): Int {

    // Read input as list of list of ints

    val lines = read_lines("src/main/resources/day02.txt")

    val reports: List<List<Int>> = lines.map { line: String ->
        val parts = line.split(" ")
        parts.map {
            s: String -> s.toInt()
        }
    }

    // Figure out which reports are safe
    val safeReports = (reports.map {
        levels: List<Int> -> day02_is_safe(levels)
    }).filter { isSafe -> isSafe }


    return safeReports.size

}

fun day02_part2(): Int {

    // Read input as list of list of ints

    val lines = read_lines("src/main/resources/day02.txt")

    val reports: List<List<Int>> = lines.map { line: String ->
        val parts = line.split(" ")
        parts.map {
            s: String -> s.toInt()
        }
    }

    val safeReports = (reports.map { levels: List<Int> -> 
        // Generate permutations by excluding items
        val permutations: List<List<Int>> = (0..levels.size).map {
            i -> levels.filterIndexed { j, _ -> j != i }
        }

        // Check if one of the permuations are safe
        permutations.map {
            perm -> day02_is_safe(perm)
        }.any { isSafe -> isSafe }
    }).filter { isSafe -> isSafe }

    return safeReports.size

}

fun main() {

    println("day02, part 1 solution is '${day02_part1()}'")
    println("day02, part 2 solution is '${day02_part2()}'")

}
