/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {

    println("day07, part 1 solution is '${Day07.part1()}'")
    println("day07, part 2 solution is '${Day07.part2()}'")

}
