/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {

    println("day06, part 1 solution is '${Day01.part1()}'")
    println("day06, part 2 solution is '${Day01.part2()}'")

}
